version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway-image
    container_name: gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
      - bd
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server-image
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share

  db:
    image: postgres:13.7-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=share
      - POSTGRES_USER=share
      - POSTGRES_PASSWORD=share
